# Generated by Django 4.0.3 on 2022-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0030_remove_blogbilgi_category_delete_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginKisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
