# Generated by Django 4.0.3 on 2022-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_kisidetay'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisidetay',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
