# Generated by Django 4.0.3 on 2022-07-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_detaykategori_kisidetay_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisidetay',
            name='category',
        ),
        migrations.DeleteModel(
            name='DetayKategori',
        ),
    ]
