# Generated by Django 4.0.3 on 2022-07-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_kisidetaylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kisiDetayList',
        ),
        migrations.AddField(
            model_name='kisidetay',
            name='url',
            field=models.URLField(default='Some String'),
        ),
        migrations.AlterField(
            model_name='kisidetay',
            name='image',
            field=models.ImageField(blank=True, upload_to='qrcode'),
        ),
    ]
