# Generated by Django 4.0.3 on 2022-07-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_delete_kisidetaylist_kisidetay_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=150, null=True)),
                ('blog_description', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
