# Generated by Django 4.0.3 on 2022-07-13 10:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_blogbilgi_blogcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='systemImageBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=150, null=True)),
                ('banner_link', models.CharField(blank=True, max_length=150, null=True)),
                ('banner_description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
