# Generated by Django 4.0.3 on 2022-07-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_systemimagebilgi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginKisi',
        ),
    ]
